### ISSUE TITLE
License issue when using Esri geometry api in Apache project

### ISSUE THREAD

**Issue by riyafa** [Esri/geometry-api-java#135] opened 2017-07-05 14:05 UTC
On trying to use this Esri geometry api in the Apache project AsterixDB a licensing issue was encountered because one of the dependencies used here is org.json. This is licensed under JSON and the JSON license is not compatible with the Apache 2.0 license[1]

[1] https://www.apache.org/legal/resolved.html#json

**Comment by randallwhitman** [comment] 2017-07-05 15:42
Looks like a duplicate of #131.

**Comment by riyafa** [comment] 2017-07-07 03:55
Sorry about that. I had already started using this API in my works with AsterixDB only to find later that it is not compatible with the  Apache license. Will this issue be fixed soon so that I can continue using it in my work or am I to look for other libraries?
Again sorry about creating noise.

**Comment by randallwhitman** [comment] 2017-08-30 21:43
@riyafa https://github.com/Esri/geometry-api-java/releases/tag/v2.0.0

**Comment by riyafa** [comment] 2017-08-31 14:51
Thank you very much. Now we can get standard GIS support for AsterixDB to its master.

**Closed** 2018-03-05 23:36 UTC
Labels: fixed_to_verify
